const root = document.querySelector('#app');
const image = (name) => `https://hotel-rosa-vetrov.ru/wp-content/uploads/2024/02/${name}.jpeg`;

root.innerHTML = `
  <div class="site-shell">
    <main id="top">
      <section class="hero"><header class="site-header"><a class="brand" href="#top" aria-label="Роза Ветров, гостевой дом в Сириусе"><span class="brand-mark">✳</span><span><strong>РОЗА ВЕТРОВ</strong></span></a><nav class="main-nav" aria-label="Основная навигация"><a href="#stay">Номера</a><a href="#about">Об отеле</a><a href="#place">Расположение</a><a href="#contacts">Контакты</a></nav><a class="header-booking" href="/booking/">Забронировать <span>↗</span></a></header><div class="hero-copy reveal"><h1>Место, где <em>море</em><br>становится частью<br>вашего дня.</h1><p class="hero-text">12 новых апартаментов рядом с Чёрным морем. Тихий дом, светлые комнаты и свой ритм отдыха.</p><div class="hero-actions"><a class="button button-dark" href="/booking/">Проверить даты <span>↗</span></a><a class="quiet-link" href="#stay">Посмотреть номера ↓</a></div></div><div class="hero-image reveal-image" style="--image: url('${image('rosa-vetrov-aparts-31')}')"><div class="hero-image-caption"><span>Роза Ветров</span><span>Сириус / Чёрное море</span></div></div></section>

      <section class="hotel-facts" id="about" aria-label="Главные факты о гостевом доме"><div class="fact reveal"><strong>12</strong><span>новых апартаментов</span></div><div class="fact reveal"><strong>Сириус</strong><span>у Чёрного моря</span></div><div class="fact reveal"><strong>20 мин</strong><span>до пляжа пешком</span></div><div class="fact reveal"><strong>35 мин</strong><span>до гор на машине</span></div></section>

      <section class="location-story reveal"><div class="location-story-media" style="--image: url('/assets/sirius-sea-mountains.png')"><span>Сириус / прогулки у моря</span></div><div class="location-story-content"><div class="location-story-title"><h2>Город рядом.<br><em>Море за окном.</em></h2></div><div class="location-story-copy"><p>Роза Ветров находится в Сириусе — спокойном районе между морем, Олимпийским парком и дорогой к Абхазии.</p><p>Здесь удобно остановиться на несколько дней, приехать с семьёй или остаться дольше, чтобы почувствовать курортный ритм без суеты.</p><a class="story-link" href="#place">Узнать больше о расположении <span>↗</span></a></div></div></section>


      <section class="stay section-space" id="stay"><div class="section-heading reveal"><h2>Выберите апартаменты<br><em>под свой ритм.</em></h2><p>Все апартаменты с отдельной спальней и гостиной. В вариантах с кухней удобно остаться подольше.</p></div><div class="rooms-list">
        <article class="room-card room-row reveal"><div class="room-photo reveal-image" style="--image: url('${image('rosa-vetrov-45-family-3')}')"></div><div class="room-detail"><div class="room-detail-top"><h3>Семейные апартаменты</h3><p>45 м² · кухня · гостиная · отдельная спальня</p></div><p class="room-description">Современная кухня со всей необходимой посудой, просторная гостиная для семейных вечеров и отдельная спальня для спокойного сна.</p><div class="room-detail-bottom"><strong>от 6 500 ₽</strong><a class="quiet-link" href="/booking/">Забронировать номер <span>↗</span></a></div></div></article>
        <article class="room-card room-row reveal"><div class="room-photo reveal-image" style="--image: url('${image('rosa-vetrov-aparts-12')}')"></div><div class="room-detail"><div class="room-detail-top"><h3>Апартаменты улучшенные</h3><p>35 м² · без кухни · для 1–3 гостей</p></div><p class="room-description">Отдельная спальня, гостиная и широкий удобный диван. Подойдут для одного или двух гостей, а также для короткого отдыха с ребёнком.</p><div class="room-detail-bottom"><strong>от 4 000 ₽</strong><a class="quiet-link" href="/booking/">Забронировать номер <span>↗</span></a></div></div></article>
        <article class="room-card room-row reveal"><div class="room-photo reveal-image" style="--image: url('${image('rosa-vetrov-aparts-20')}')"></div><div class="room-detail"><div class="room-detail-top"><h3>Двухкомнатные апартаменты</h3><p>45 м² · кухня · душ · прихожая</p></div><p class="room-description">Гостиная с кухней, просторная спальня и большой санузел с душевой кабиной. Всё необходимое для комфортного проживания.</p><div class="room-detail-bottom"><strong>от 6 000 ₽</strong><a class="quiet-link" href="/booking/">Забронировать номер <span>↗</span></a></div></div></article>
        <article class="room-card room-row reveal"><div class="room-photo reveal-image" style="--image: url('${image('rosa-vetrov-aparts-11')}')"></div><div class="room-detail"><div class="room-detail-top"><h3>Двухкомнатные без кухни</h3><p>35 м² · спальня · гостиная · широкий диван</p></div><p class="room-description">Светлые апартаменты со своей гостиной и спальней. Комфортный вариант для одного или двух гостей, которым важны пространство и тишина.</p><div class="room-detail-bottom"><strong>от 4 500 ₽</strong><a class="quiet-link" href="/booking/">Забронировать номер <span>↗</span></a></div></div></article>
      </div></section>

      <section class="offers section-space" id="offers"><div class="section-heading reveal"><h2>Акции<br><em>и специальные условия.</em></h2><p>Выберите подходящую акцию и свяжитесь с нами по телефону, чтобы забронировать апартаменты на специальных условиях.</p></div><div class="offer-cards"><article class="offer-card reveal"><div class="offer-card-top"><span>−10%</span></div><h3>Заранее — выгоднее.</h3><p>Бронируйте и оплачивайте апартаменты заранее и получайте скидку 10% от стоимости. Акция действует, если между датой бронирования и датой заезда более 60 дней.</p><a class="quiet-link" href="tel:+79388785405">Забронировать по телефону ↗</a></article><article class="offer-card offer-card-featured reveal"><div class="offer-card-top"><span>−15%</span></div><h3>Оставайтесь<br>на месяц.</h3><p>Сделаем скидку 15% при бронировании апартаментов на срок 30 дней и больше.</p><a class="quiet-link" href="tel:+79388785405">Забронировать по телефону ↗</a></article><article class="offer-card reveal"><div class="offer-card-top"><span>−10%</span></div><h3>Праздник<br>у моря.</h3><p>Скидка 10% действует за 3 дня до дня рождения, в день рождения и 3 дня после него.</p><a class="quiet-link" href="tel:+79388785405">Забронировать по телефону ↗</a></article></div></section>

      <section class="gallery section-space" id="gallery"><div class="gallery-heading reveal"><h2>Посмотрите<br><em>Розу Ветров.</em></h2><div class="gallery-tabs" aria-label="Категории галереи"><span class="active">Гостевой дом</span><span>Номера</span><span>Кафе</span><span>Сириус и окружение</span></div></div><div class="gallery-grid"><figure class="gallery-item gallery-main reveal-image"><div class="gallery-photo" style="--image: url('${image('rosa-vetrov-aparts-36')}')"></div><figcaption>Гостевой дом</figcaption></figure><figure class="gallery-item gallery-room reveal-image"><div class="gallery-photo" style="--image: url('${image('rosa-vetrov-aparts-12')}')"></div><figcaption>Номер</figcaption></figure><figure class="gallery-item gallery-cafe reveal-image"><div class="gallery-photo" style="--image: url('${image('rosa-vetrov-aparts-27')}')"></div><figcaption>Кафе и общие пространства</figcaption></figure><figure class="gallery-item gallery-detail reveal-image"><div class="gallery-photo" style="--image: url('${image('rosa-vetrov-aparts-20')}')"></div><figcaption>Детали интерьера</figcaption></figure><figure class="gallery-item gallery-place reveal-image"><div class="gallery-photo" style="--image: url('${image('rosa-vetrov-aparts-9')}')"></div><figcaption>Сириус и прогулки у моря</figcaption></figure></div></section>

      <section class="editorial-feature section-space" id="cafe"><div class="feature-photo reveal-image" style="--image: url('/assets/cafe-breakfast.png')"></div><div class="feature-copy reveal"><h2>Кофе, завтрак<br><em>и никуда не спешить.</em></h2><p>Каждое утро с 8 часов во дворе гостевого дома мы готовим сытные завтраки и варим ароматный кофе.</p><a class="quiet-link" href="#contacts">Узнать больше ↗</a></div></section>

      <div class="location-cards"><section class="welcome section-space"><div class="section-intro reveal"><h2>Выберите проживание<br><em>под свой ритм.</em></h2></div><div class="welcome-copy reveal"><p>Мы открылись в 2024 году, чтобы отдых в Сириусе был похож на обычную хорошую жизнь: с завтраком во дворе, большим окном и временем на прогулку.</p><div class="distance-row"><span><strong>20 мин</strong>до моря пешком</span><span><strong>4 мин</strong>на машине</span><span><strong>6 мин</strong>до Абхазии</span></div></div></section><section class="place section-space" id="place"><div class="place-copy reveal"><h2>Всё нужное<br><em>рядом.</em></h2><p>До моря можно дойти через Олимпийский парк, а на машине легко отправиться в Красную Поляну или Абхазию.</p><div class="place-facts"><span><strong>35 мин</strong>Красная Поляна</span><span><strong>25 мин</strong>Морпорт Сочи</span></div></div><div class="place-photo reveal-image" style="--image: url('${image('rosa-vetrov-aparts-9')}')"></div></section></div>


      <section class="reviews section-space" id="reviews"><div class="reviews-heading reveal"><h2>Отзывы наших гостей</h2></div><div class="review-cards"><article class="review-card reveal"><div class="review-card-head"><span class="review-avatar avatar-vasiliy">ВО</span><div><h3>Василий О.</h3><div class="stars" aria-label="5 из 5">★★★★★</div><p>Москва</p></div><span class="source-mark source-trip">●</span></div><p class="review-quote">Приезжал на выходные отдохнуть к морю. Гостиница хорошая. Везде чисто и уютно, в номерах убирают часто. Вежливый и общительный персонал. Цена приемлемая. Спасибо. Рекомендую. Все понравилось</p></article><article class="review-card reveal"><div class="review-card-head"><span class="review-avatar avatar-maria">МЯ</span><div><h3>Мария Я.</h3><div class="stars" aria-label="5 из 5">★★★★★</div><p>Воронеж</p></div><span class="source-mark source-yandex">Я</span></div><p class="review-quote">Поехали в зимние праздники отдохнуть с мамой и дочерью на морское побережье. Вежливый персонал и прекрасная погода сделали наши выходные великолепными. Планируем вернуться еще.</p></article><article class="review-card reveal"><div class="review-card-head"><span class="review-avatar avatar-nikita">НС</span><div><h3>Никита С.</h3><div class="stars" aria-label="5 из 5">★★★★★</div><p>Волгоград</p></div><span class="source-mark source-google">G+</span></div><p class="review-quote">Хочу написать пару слов про это гостеприимное место, персонал приветливый, в комнатах чистенько и уютно и парковка удобная, рекомендую данный гостевой дом.</p></article></div></section>

      <section class="faq section-space" id="faq"><div class="faq-heading reveal"><h2>Вопросы о гостевом доме</h2></div><div class="faq-list reveal"><details open><summary><span class="faq-icon"></span>Можно ли приехать к вам на машине?</summary><div class="faq-answer"><p>Да, около нашего гостевого дома есть много бесплатных парковочных мест. На машине удобно съездить в Красную Поляну или Абхазию: всё рядом, а дороги хорошие.</p></div></details><details><summary><span class="faq-icon"></span>Принимаете ли вы гостей с детьми?</summary><div class="faq-answer"><p>Да, конечно. Во всех апартаментах есть гостиная, где на диване можно организовать спальное место для ребёнка. Для семейного отдыха особенно удобны номера с кухней.</p></div></details><details><summary><span class="faq-icon"></span>Далеко ли от вас до моря?</summary><div class="faq-answer"><p>На машине дорога до моря занимает около 4 минут. Пешком можно дойти примерно за 20 минут через Олимпийский парк, мимо стадиона Фишт и ледовой арены Айсберг. Также можно заказать электрокар до пляжа.</p></div></details></div></section>

      <section class="contacts section-space" id="contacts"><div class="contacts-top reveal"><div class="contacts-heading"><h2>Контакты</h2><p>Будем рады ответить на вопросы, помочь выбрать апартаменты и встретить вас в Сириусе.</p></div><div class="contact-list"><a href="https://yandex.ru/maps/?text=Сочи%20Сириус%20Субтропическая%205%2F1" target="_blank" rel="noreferrer"><span>Адрес</span><strong>г. Сочи, пгт. Сириус,<br>ул. Субтропическая, 5/1</strong></a><a href="tel:+79388785405"><span>Телефон</span><strong>+7 938 878-54-05</strong></a><a href="https://wa.me/79388785405" target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>+7 938 878-54-05</strong></a><a href="https://t.me/rosa_vetrov" target="_blank" rel="noreferrer"><span>Telegram</span><strong>@rosa_vetrov</strong></a></div></div><div class="map-art reveal-image" role="img" aria-label="Схематичная карта расположения гостевого дома Роза Ветров в Сириусе"><div class="map-road map-road-one"></div><div class="map-road map-road-two"></div><div class="map-road map-road-three"></div><div class="map-water"></div><div class="map-label map-label-park">ОЛИМПИЙСКИЙ ПАРК</div><div class="map-label map-label-sea">ЧЁРНОЕ МОРЕ</div><div class="map-label map-label-house">РОЗА ВЕТРОВ<div class="map-pin"></div></div><div class="map-coordinates">43°24' N&nbsp;&nbsp;39°56' E</div></div></section>
    </main>
    <footer class="site-footer"><div class="footer-main"><div class="footer-brand"><a class="brand" href="#top" aria-label="Роза Ветров, гостевой дом в Сириусе"><span class="brand-mark">✳</span><span><strong>РОЗА ВЕТРОВ</strong><small>Сириус · Чёрное море</small></span></a><p>Тихий дом для отдыха у моря,<br>парка и горных маршрутов.</p></div><div class="footer-column"><h3>Отель</h3><a href="#about">Об отеле</a><a href="#stay">Номера</a><a href="#gallery">Фотогалерея</a><a href="#place">Расположение</a></div><div class="footer-column"><h3>Гостям</h3><a href="/booking/">Бронирование</a><a href="#contacts">Контакты</a><a href="#faq">Частые вопросы</a></div><div class="footer-column footer-contacts"><h3>Контакты</h3><a href="tel:+79388785405">+7 938 878-54-05</a><a href="https://t.me/rosa_vetrov" target="_blank" rel="noreferrer">@rosa_vetrov</a><span>г. Сочи, пгт. Сириус,<br>ул. Субтропическая, 5/1</span></div></div><div class="footer-bottom"><span>© Роза Ветров, 2026</span><span>Сириус · Краснодарский край</span><a href="#top">Наверх ↑</a></div></footer>
  </div>`;

if (window.gsap && window.ScrollTrigger) { gsap.registerPlugin(ScrollTrigger); gsap.utils.toArray('.reveal').forEach((el) => gsap.fromTo(el, {opacity:0,y:28}, {opacity:1,y:0,duration:.9,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 86%'}})); gsap.utils.toArray('.reveal-image').forEach((el) => gsap.fromTo(el, {opacity:.45,scale:.94}, {opacity:1,scale:1,duration:1.1,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 90%',end:'top 45%',scrub:true}})); }

